FROM python:alpine3.13

RUN apk update && \
    apk add --no-cache --virtual build-deps gcc python3-dev musl-dev && \
    apk add postgresql-dev

WORKDIR /tests

COPY ./tests/requests.txt .

RUN pip install -r requests.txt

COPY ./tests .
