FROM python:alpine3.13

RUN apk update && \
    apk add --no-cache --virtual build-deps gcc python3-dev musl-dev && \
    apk add postgresql-dev

COPY ./.env .

WORKDIR /tests

COPY ./tests/requirements.txt .

RUN pip install -r requirements.txt

COPY ./tests .
